version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:unit
workflows:
  run_unt_tests:
    jobs:
      - test
