version: 2.1

orbs:
  node: circleci/node@2

  jobs:
  test:
    docker:
      - image: circleci/node:11.8-browsers

    steps:
      - checkout # special step to check out source code to working directory
      - node/install-packages:
          pkg-manager: npm
          cache-key: 'npm.lock'
      - run:
          name: running unit tests
          command: npm run test:unit

workflows:
  version: 2
  test:
    jobs:
      - test
