version: '2.1'
orbs:
  node: circleci/node@4.5.1
  aws-cli: circleci/aws-cli@2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:unit
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
